[tool.black]
line-length = 110
target-version = ['py39', 'py310']
include = '\.py$'
force-exclude = '''
/(
    | rare/ui
    | rare/legendary
    | rare/resources
)/
'''

[tool.poetry]
name = "rare"
version = "1.9.0-rc.2"
description = "A GUI for Legendary"
authors = ["Dummerle"]
license = "GPL3"
readme = "README.md"
repository = "https://github.com/Dummerle/Rare"

[tool.poetry.dependencies]
python = "^3.8"
PyQt5 = "^5.15.7"
requests = "^2.28.1"
QtAwesome = "^1.1.1"
pypresence = { version = "^4.2.1", optional = true }
pywin32 = { version = "^304", markers = "platform_system == 'Windows'" }
pywebview = [
    { version = "^3.6.3", extras = ["cef"], platform = "windows", optional = true },
    { version = "^3.6.3", extras = ["gtk"], platform = "linux", optional = true },
]
legendary-gl = "^0.20.28"
typing-extensions = "^4.3.0"


[tool.poetry.scripts]
start = "rare.__main__:main"



[tool.poetry.dev-dependencies]
Nuitka = "^1.0.6"
pylint = "^2.15.0"
black = "^22.6.0"

#[build-system]
#requires = ["setuptools>=42"z, "wheel", "nuitka", "toml"]
#build-backend = "nuitka.distutils.Build"


[nuitka]
show-scons = true
enable-plugin = ["pyqt5", "anti-bloat"]
show-anti-bloat-changes = true
nofollow-import-to = ["*.tests", "*.distutils"]
